maintainer "Graham Hughes"
maintainer_email "graham@rightscale.com"
license "MIT"
description "Install and run Hudson on Ubuntu/Debian"
version "0.1"
depends "apt"
supports "ubuntu"
supports "debian"

recipe "hudson::repository", "Sets up Hudson repository"
recipe "hudson::update", "Updates Hudson instance"
recipe "hudson::shutdown", "Shuts the Hudson instance down"
recipe "hudson", "Starts local Hudson master"
